version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.example
    environment:
      MYSQL_HOST: db
    volumes:
      - ".:/go/src/github.com/OdaDaisuke/grpc_shopping/server"
    working_dir: /go/src/github.com/OdaDaisuke/grpc_shopping/server
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: shopping
      MYSQL_USER: daisuke
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
    driver: local