// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package item

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item_Stock int32

const (
	Item_Enough  Item_Stock = 0
	Item_Short   Item_Stock = 1
	Item_Unknown Item_Stock = 2
)

var Item_Stock_name = map[int32]string{
	0: "Enough",
	1: "Short",
	2: "Unknown",
}

var Item_Stock_value = map[string]int32{
	"Enough":  0,
	"Short":   1,
	"Unknown": 2,
}

func (x Item_Stock) String() string {
	return proto.EnumName(Item_Stock_name, int32(x))
}

func (Item_Stock) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2, 0}
}

type GetAllMessage struct {
	Page                 string   `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllMessage) Reset()         { *m = GetAllMessage{} }
func (m *GetAllMessage) String() string { return proto.CompactTextString(m) }
func (*GetAllMessage) ProtoMessage()    {}
func (*GetAllMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *GetAllMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllMessage.Unmarshal(m, b)
}
func (m *GetAllMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllMessage.Marshal(b, m, deterministic)
}
func (m *GetAllMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllMessage.Merge(m, src)
}
func (m *GetAllMessage) XXX_Size() int {
	return xxx_messageInfo_GetAllMessage.Size(m)
}
func (m *GetAllMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllMessage proto.InternalMessageInfo

func (m *GetAllMessage) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

type GetAllResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ThumbnailSrc         string     `protobuf:"bytes,2,opt,name=thumbnailSrc,proto3" json:"thumbnailSrc,omitempty"`
	Description          string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                int32      `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock                Item_Stock `protobuf:"varint,5,opt,name=stock,proto3,enum=Item_Stock" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetThumbnailSrc() string {
	if m != nil {
		return m.ThumbnailSrc
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetStock() Item_Stock {
	if m != nil {
		return m.Stock
	}
	return Item_Enough
}

func init() {
	proto.RegisterEnum("Item_Stock", Item_Stock_name, Item_Stock_value)
	proto.RegisterType((*GetAllMessage)(nil), "GetAllMessage")
	proto.RegisterType((*GetAllResponse)(nil), "GetAllResponse")
	proto.RegisterType((*Item)(nil), "Item")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0xb7, 0xbb, 0x14, 0xb3, 0x83, 0x22, 0x99, 0x78, 0x68, 0xf4, 0x82, 0xf5, 0x42, 0xb2,
	0x91, 0x03, 0xfa, 0x02, 0x1e, 0x8c, 0xf1, 0xe0, 0x05, 0xe2, 0x03, 0xb0, 0x38, 0x01, 0xb2, 0xd0,
	0x12, 0xda, 0x8d, 0x6f, 0xe8, 0x73, 0x99, 0x96, 0xc4, 0xc8, 0x6d, 0xfe, 0x7f, 0x26, 0x5f, 0x26,
	0x1f, 0x40, 0x6f, 0x69, 0xcc, 0xa7, 0x59, 0x5b, 0x2d, 0x1f, 0xe0, 0xea, 0x8d, 0xec, 0xcb, 0x30,
	0x7c, 0x90, 0x31, 0x75, 0x4b, 0x88, 0x10, 0x4c, 0x75, 0x4b, 0x82, 0xa5, 0x2c, 0xdb, 0x97, 0x7e,
	0x96, 0x8f, 0x10, 0x2f, 0x47, 0x25, 0x99, 0x49, 0x2b, 0x43, 0x78, 0x07, 0xdc, 0x41, 0x8c, 0x60,
	0xe9, 0x2e, 0x8b, 0x0a, 0x9e, 0xbf, 0x5b, 0x1a, 0xcb, 0xa5, 0x93, 0x3f, 0x0c, 0x02, 0x97, 0x1d,
	0x4b, 0xd5, 0xe3, 0x1f, 0xcb, 0xcd, 0x28, 0xe1, 0xd2, 0x76, 0xe7, 0xf1, 0xa8, 0xea, 0x7e, 0xa8,
	0xe6, 0x46, 0x6c, 0xfd, 0x6e, 0xd5, 0x61, 0x0a, 0xd1, 0x17, 0x99, 0x66, 0xee, 0x27, 0xdb, 0x6b,
	0x25, 0x76, 0xfe, 0xe4, 0x7f, 0x85, 0x37, 0xc0, 0xa7, 0xb9, 0x6f, 0x48, 0x04, 0x29, 0xcb, 0x78,
	0xb9, 0x04, 0xbc, 0x07, 0x6e, 0xac, 0x6e, 0x4e, 0x82, 0xa7, 0x2c, 0x8b, 0x8b, 0xc8, 0x7f, 0x95,
	0x57, 0xae, 0x2a, 0x97, 0x8d, 0x3c, 0x00, 0xf7, 0x19, 0x01, 0xc2, 0x57, 0xa5, 0xcf, 0x6d, 0x97,
	0x6c, 0x70, 0x0f, 0xbc, 0xea, 0xf4, 0x6c, 0x13, 0x86, 0x11, 0x5c, 0x7c, 0xaa, 0x93, 0xd2, 0xdf,
	0x2a, 0xd9, 0x16, 0xcf, 0xc0, 0x1d, 0xc1, 0xe0, 0x01, 0xc2, 0x45, 0x00, 0xc6, 0xf9, 0x4a, 0xd7,
	0xed, 0x75, 0xbe, 0x36, 0x23, 0x37, 0xc7, 0xd0, 0x9b, 0x7d, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0xf2, 0x4d, 0xe5, 0x67, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemsClient is the client API for Items service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemsClient interface {
	GetAll(ctx context.Context, in *GetAllMessage, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type itemsClient struct {
	cc *grpc.ClientConn
}

func NewItemsClient(cc *grpc.ClientConn) ItemsClient {
	return &itemsClient{cc}
}

func (c *itemsClient) GetAll(ctx context.Context, in *GetAllMessage, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/Items/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemsServer is the server API for Items service.
type ItemsServer interface {
	GetAll(context.Context, *GetAllMessage) (*GetAllResponse, error)
}

// UnimplementedItemsServer can be embedded to have forward compatible implementations.
type UnimplementedItemsServer struct {
}

func (*UnimplementedItemsServer) GetAll(ctx context.Context, req *GetAllMessage) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}

func RegisterItemsServer(s *grpc.Server, srv ItemsServer) {
	s.RegisterService(&_Items_serviceDesc, srv)
}

func _Items_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Items/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServer).GetAll(ctx, req.(*GetAllMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Items_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Items",
	HandlerType: (*ItemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _Items_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}
