// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_Status int32

const (
	User_Normal       User_Status = 0
	User_Ban          User_Status = 1
	User_Unsubscribed User_Status = 2
)

var User_Status_name = map[int32]string{
	0: "Normal",
	1: "Ban",
	2: "Unsubscribed",
}

var User_Status_value = map[string]int32{
	"Normal":       0,
	"Ban":          1,
	"Unsubscribed": 2,
}

func (x User_Status) String() string {
	return proto.EnumName(User_Status_name, int32(x))
}

func (User_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8, 0}
}

// signup
type SignupMessage struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupMessage) Reset()         { *m = SignupMessage{} }
func (m *SignupMessage) String() string { return proto.CompactTextString(m) }
func (*SignupMessage) ProtoMessage()    {}
func (*SignupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SignupMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupMessage.Unmarshal(m, b)
}
func (m *SignupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupMessage.Marshal(b, m, deterministic)
}
func (m *SignupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupMessage.Merge(m, src)
}
func (m *SignupMessage) XXX_Size() int {
	return xxx_messageInfo_SignupMessage.Size(m)
}
func (m *SignupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignupMessage proto.InternalMessageInfo

func (m *SignupMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Authenticate
type AuthenticateMessage struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateMessage) Reset()         { *m = AuthenticateMessage{} }
func (m *AuthenticateMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticateMessage) ProtoMessage()    {}
func (*AuthenticateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *AuthenticateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateMessage.Unmarshal(m, b)
}
func (m *AuthenticateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateMessage.Marshal(b, m, deterministic)
}
func (m *AuthenticateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateMessage.Merge(m, src)
}
func (m *AuthenticateMessage) XXX_Size() int {
	return xxx_messageInfo_AuthenticateMessage.Size(m)
}
func (m *AuthenticateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateMessage proto.InternalMessageInfo

func (m *AuthenticateMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticateMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Delete
type DeleteMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessage) Reset()         { *m = DeleteMessage{} }
func (m *DeleteMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteMessage) ProtoMessage()    {}
func (*DeleteMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessage.Unmarshal(m, b)
}
func (m *DeleteMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessage.Marshal(b, m, deterministic)
}
func (m *DeleteMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessage.Merge(m, src)
}
func (m *DeleteMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteMessage.Size(m)
}
func (m *DeleteMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessage proto.InternalMessageInfo

func (m *DeleteMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// UpdateProfile
type UpdateProfileMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfileImageSrc      string   `protobuf:"bytes,3,opt,name=profileImageSrc,proto3" json:"profileImageSrc,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileMessage) Reset()         { *m = UpdateProfileMessage{} }
func (m *UpdateProfileMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileMessage) ProtoMessage()    {}
func (*UpdateProfileMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UpdateProfileMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileMessage.Unmarshal(m, b)
}
func (m *UpdateProfileMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileMessage.Marshal(b, m, deterministic)
}
func (m *UpdateProfileMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileMessage.Merge(m, src)
}
func (m *UpdateProfileMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileMessage.Size(m)
}
func (m *UpdateProfileMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileMessage proto.InternalMessageInfo

func (m *UpdateProfileMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProfileMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProfileMessage) GetProfileImageSrc() string {
	if m != nil {
		return m.ProfileImageSrc
	}
	return ""
}

func (m *UpdateProfileMessage) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UpdateProfileMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateProfileMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateProfileResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileResponse) Reset()         { *m = UpdateProfileResponse{} }
func (m *UpdateProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileResponse) ProtoMessage()    {}
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UpdateProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileResponse.Unmarshal(m, b)
}
func (m *UpdateProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileResponse.Merge(m, src)
}
func (m *UpdateProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileResponse.Size(m)
}
func (m *UpdateProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileResponse proto.InternalMessageInfo

func (m *UpdateProfileResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

//------ Model ------
type User struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfileImageSrc      string      `protobuf:"bytes,3,opt,name=profileImageSrc,proto3" json:"profileImageSrc,omitempty"`
	Bio                  string      `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Email                string      `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string      `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Status               User_Status `protobuf:"varint,7,opt,name=status,proto3,enum=User_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetProfileImageSrc() string {
	if m != nil {
		return m.ProfileImageSrc
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetStatus() User_Status {
	if m != nil {
		return m.Status
	}
	return User_Normal
}

func init() {
	proto.RegisterEnum("User_Status", User_Status_name, User_Status_value)
	proto.RegisterType((*SignupMessage)(nil), "SignupMessage")
	proto.RegisterType((*SignupResponse)(nil), "SignupResponse")
	proto.RegisterType((*AuthenticateMessage)(nil), "AuthenticateMessage")
	proto.RegisterType((*AuthenticateResponse)(nil), "AuthenticateResponse")
	proto.RegisterType((*DeleteMessage)(nil), "DeleteMessage")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*UpdateProfileMessage)(nil), "UpdateProfileMessage")
	proto.RegisterType((*UpdateProfileResponse)(nil), "UpdateProfileResponse")
	proto.RegisterType((*User)(nil), "User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xdf, 0x8a, 0xd4, 0x30,
	0x14, 0xc6, 0xdb, 0x4e, 0xdb, 0xd5, 0xe3, 0x4c, 0xa7, 0x1c, 0x3b, 0x43, 0xed, 0xd5, 0x12, 0x04,
	0x0b, 0x0b, 0x11, 0xeb, 0xb5, 0xe0, 0x8a, 0x20, 0x7b, 0xa1, 0xc8, 0x0c, 0xf3, 0x00, 0xe9, 0x34,
	0x8e, 0x81, 0xfe, 0x23, 0x69, 0xf1, 0x95, 0x7c, 0x2e, 0x5f, 0xc0, 0x57, 0x90, 0x26, 0xb3, 0xdd,
	0xed, 0x52, 0x61, 0xf1, 0xca, 0xbb, 0x9c, 0x73, 0x92, 0xef, 0x4b, 0xce, 0xf9, 0x05, 0xa0, 0x57,
	0x5c, 0xd2, 0x56, 0x36, 0x5d, 0x43, 0xae, 0x61, 0xb5, 0x17, 0xa7, 0xba, 0x6f, 0x3f, 0x73, 0xa5,
	0xd8, 0x89, 0x63, 0x04, 0x1e, 0xaf, 0x98, 0x28, 0x63, 0xfb, 0xd2, 0x4e, 0x9f, 0xee, 0x4c, 0x80,
	0x09, 0x3c, 0x69, 0x99, 0x52, 0x3f, 0x1a, 0x59, 0xc4, 0x8e, 0x2e, 0x8c, 0x31, 0xb9, 0x82, 0xc0,
	0x48, 0xec, 0xb8, 0x6a, 0x9b, 0x5a, 0x71, 0x7c, 0x01, 0xee, 0x60, 0xa1, 0x25, 0x9e, 0x65, 0x1e,
	0x3d, 0x28, 0x2e, 0x77, 0x3a, 0x45, 0x3e, 0xc1, 0xf3, 0xeb, 0xbe, 0xfb, 0xce, 0xeb, 0x4e, 0x1c,
	0x59, 0xc7, 0xff, 0xdd, 0xf5, 0x0d, 0x44, 0xf7, 0x85, 0x1e, 0xe3, 0xfd, 0x0a, 0x56, 0x1f, 0x79,
	0xc9, 0xef, 0x5c, 0xb7, 0xe0, 0x0f, 0x85, 0x9b, 0xe2, 0x6c, 0x7b, 0x8e, 0x48, 0x0a, 0x81, 0xd9,
	0x38, 0xaa, 0x6e, 0xc1, 0x57, 0x1d, 0xeb, 0x7a, 0x75, 0xbb, 0xd3, 0x44, 0xe4, 0xa7, 0x0d, 0xd1,
	0xa1, 0x2d, 0x58, 0xc7, 0xbf, 0xca, 0xe6, 0x9b, 0x28, 0x47, 0xe9, 0x00, 0x1c, 0x71, 0x2b, 0xeb,
	0x88, 0x02, 0x11, 0xdc, 0x9a, 0x55, 0xfc, 0xfc, 0x0c, 0xbd, 0xc6, 0x14, 0xd6, 0xad, 0x39, 0x75,
	0x53, 0xb1, 0x13, 0xdf, 0xcb, 0x63, 0xbc, 0xd0, 0xe5, 0x87, 0x69, 0x0c, 0x61, 0x91, 0x8b, 0x26,
	0x76, 0x75, 0x75, 0x58, 0xde, 0x35, 0xcc, 0xfb, 0x5b, 0xc3, 0xfc, 0x07, 0x0d, 0xcb, 0x60, 0x33,
	0xb9, 0xe9, 0x63, 0x3a, 0xf6, 0xdb, 0x06, 0x77, 0x08, 0xff, 0xbf, 0xe7, 0xe0, 0xcb, 0x71, 0x22,
	0x17, 0x97, 0x76, 0x1a, 0x64, 0x4b, 0x7d, 0x6f, 0xba, 0xd7, 0xb9, 0x71, 0x3e, 0xaf, 0xc1, 0x37,
	0x19, 0x04, 0xf0, 0xbf, 0x34, 0xb2, 0x62, 0x65, 0x68, 0xe1, 0x05, 0x2c, 0x3e, 0xb0, 0x3a, 0xb4,
	0x31, 0x84, 0xe5, 0xa1, 0x56, 0x7d, 0xae, 0x8e, 0x52, 0xe4, 0xbc, 0x08, 0x9d, 0xec, 0x97, 0x0d,
	0xde, 0x20, 0xa4, 0xf0, 0x0a, 0x7c, 0x83, 0x35, 0x06, 0x74, 0xf2, 0x45, 0x92, 0x35, 0x9d, 0xf2,
	0x4e, 0x2c, 0x7c, 0x07, 0xcb, 0xfb, 0x34, 0x62, 0x44, 0x67, 0x28, 0x4f, 0x36, 0x74, 0x0e, 0x59,
	0x62, 0x0d, 0x5e, 0x06, 0x38, 0x0c, 0xe8, 0x04, 0xd1, 0x64, 0x4d, 0xa7, 0x24, 0x12, 0x0b, 0xdf,
	0xc3, 0x6a, 0x32, 0x48, 0xdc, 0xd0, 0x39, 0x04, 0x93, 0x2d, 0x9d, 0x9d, 0x37, 0xb1, 0x72, 0x5f,
	0xff, 0xfd, 0xb7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x88, 0xbd, 0x4a, 0x09, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	Signup(ctx context.Context, in *SignupMessage, opts ...grpc.CallOption) (*SignupResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateMessage, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	Delete(ctx context.Context, in *DeleteMessage, opts ...grpc.CallOption) (*DeleteResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileMessage, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Signup(ctx context.Context, in *SignupMessage, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/Users/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Authenticate(ctx context.Context, in *AuthenticateMessage, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/Users/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Delete(ctx context.Context, in *DeleteMessage, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/Users/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateProfile(ctx context.Context, in *UpdateProfileMessage, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, "/Users/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	Signup(context.Context, *SignupMessage) (*SignupResponse, error)
	Authenticate(context.Context, *AuthenticateMessage) (*AuthenticateResponse, error)
	Delete(context.Context, *DeleteMessage) (*DeleteResponse, error)
	UpdateProfile(context.Context, *UpdateProfileMessage) (*UpdateProfileResponse, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) Signup(ctx context.Context, req *SignupMessage) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedUsersServer) Authenticate(ctx context.Context, req *AuthenticateMessage) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedUsersServer) Delete(ctx context.Context, req *DeleteMessage) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedUsersServer) UpdateProfile(ctx context.Context, req *UpdateProfileMessage) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Signup(ctx, req.(*SignupMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Authenticate(ctx, req.(*AuthenticateMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Delete(ctx, req.(*DeleteMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateProfile(ctx, req.(*UpdateProfileMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Users_Signup_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _Users_Authenticate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Users_Delete_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _Users_UpdateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
